In [11]:
print('Hello')

Hello


In [42]:
def Mahadi(a,b,c):
    p = a+b*c
    return p

def Hasan(p,q):
    if(p==q):
        return p
    else:
        return q
    
print(Hasan(10,9))
print("Do you know the result?", "The result is: ", Mahadi(2,3,4))

cities = ["Paris", "Tokyo", "Amsterdam"]
for city in cities:
    print(city)

i = 1

mark = [1,2,4,5,6,7]
for m in mark:
    print( i , " mark is: ", m*3)
    i=i+1

9
Do you know the result? The result is:  14
Paris
Tokyo
Amsterdam
1  mark is:  3
2  mark is:  6
3  mark is:  12
4  mark is:  15
5  mark is:  18
6  mark is:  21


In [34]:
def add(a, b):
    return a + b

print(add(5, 3))  

8


In [13]:
def find_max(numbers):
    max_num = numbers[0]
    for num in numbers:
        if num > max_num:
            max_num = num
    return max_num


print(find_max([3, 7, 2, 9, 5]))

9


In [14]:
def count_even(numbers):
    count = 0
    for num in numbers:
        if num % 2 == 0:
            count += 1
    return count

print(count_even([1, 2, 3, 4, 5, 6]))  

3


In [15]:
def reverse_list(numbers):
    reversed_list = []
    for i in range(len(numbers) - 1, -1, -1):
        reversed_list.append(numbers[i])
    return reversed_list

print(reverse_list([1, 2, 3, 4]))

[4, 3, 2, 1]


In [16]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(5))

120


**Bellow code is about Problram 7**

In [17]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/8.7 MB 6.9 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.7 MB 5.2 MB/s eta 0:00:02
   --------------------- ------------------ 4.7/8.7 MB 8.4 MB/s eta 0:00:01
   ------------------------------------- -- 8.1/8.7 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 10.4 MB/s  0:00:00
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.8 MB 18.1 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.8 MB 18.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 16.8 MB/s  0:00:00
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---- ----------------------------------- 3.9/38.5 MB 19.3 MB/s eta 0:00:02
   -------- -----------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

class LabelClass:
    def __init__(self, cities):
        self.cities = cities
        self.label_encoder = LabelEncoder()
        self.onehot_encoder = OneHotEncoder(sparse_output=False)
        
    def label_encode(self):
        labels = self.label_encoder.fit_transform(self.cities)
        return labels
    
    def one_hot_encode(self):
        labels = self.label_encoder.fit_transform(self.cities)
        labels_reshaped = labels.reshape(-1, 1)
        onehot = self.onehot_encoder.fit_transform(labels_reshaped)
        return onehot
cities = ["paris", "paris", "tokyo", "amsterdam"]
labeler = LabelClass(cities)

print("Label Encoded:", labeler.label_encode())
print("One Hot Encoded:\n", labeler.one_hot_encode())

Label Encoded: [1 1 2 0]
One Hot Encoded:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [19]:
import math

# Example number
num = 16

square_root = math.sqrt(num)
power = math.pow(num, 2)

print("Square root of", num, "is:", square_root)
print(num, "to the power 2 is:", power)

Square root of 16 is: 4.0
16 to the power 2 is: 256.0


In [20]:
import random

numbers = [random.randint(1, 50) for _ in range(5)]
print("5 Random Numbers between 1 and 50:", numbers)

5 Random Numbers between 1 and 50: [43, 22, 42, 26, 36]


In [21]:
import datetime

current_time = datetime.datetime.now()
print("Current Date and Time:", current_time)

Current Date and Time: 2025-11-01 12:27:51.641254


In [22]:
import os

cwd = os.getcwd()
print("Current Working Directory:", cwd)

Current Working Directory: d:\Python-Foundation
